import {
  STEAMM_PKG_ID,
  STEAMM_PUBLISHED_AT,
  STEAMM_SCRIPT_PKG_ID,
  STEAMM_SCRIPT_PUBLISHED_AT,
} from "../../../config/mainnet";
import {
  STEAMM_BETA_PKG_ID,
  STEAMM_BETA_PUBLISHED_AT,
  STEAMM_SCRIPT_BETA_PKG_ID,
  STEAMM_SCRIPT_BETA_PUBLISHED_AT,
} from "../../../config/mainnetBeta";

export const PACKAGE_ID = process.env.NEXT_PUBLIC_STEAMM_USE_BETA_MARKET
  ? STEAMM_BETA_PKG_ID
  : STEAMM_PKG_ID;
export let PUBLISHED_AT = process.env.NEXT_PUBLIC_STEAMM_USE_BETA_MARKET
  ? STEAMM_BETA_PUBLISHED_AT
  : STEAMM_PUBLISHED_AT;
export const PKG_V1 = process.env.NEXT_PUBLIC_STEAMM_USE_BETA_MARKET
  ? STEAMM_BETA_PKG_ID
  : STEAMM_PKG_ID;

export const SCRIPT_PACKAGE_ID = process.env.NEXT_PUBLIC_STEAMM_USE_BETA_MARKET
  ? STEAMM_SCRIPT_BETA_PKG_ID
  : STEAMM_SCRIPT_PKG_ID;
export const SCRIPT_PUBLISHED_AT = process.env.NEXT_PUBLIC_STEAMM_USE_BETA_MARKET
  ? STEAMM_SCRIPT_BETA_PUBLISHED_AT
  : STEAMM_SCRIPT_PUBLISHED_AT;
export const SCRIPT_PKG_V1 = process.env.NEXT_PUBLIC_STEAMM_USE_BETA_MARKET
  ? STEAMM_SCRIPT_BETA_PKG_ID
  : STEAMM_SCRIPT_PKG_ID;

export function setPublishedAt(publishedAt: string) {
  PUBLISHED_AT = publishedAt;
}
